
development:
  adapter: postgresql
  encoding: unicode
  database: spreeDemo_development
  pool: 5
  timeout: 5000
  username: nut
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: spreeDemo_test
  pool: 5
  timeout: 5000
  username: nut
  password:
